apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-web
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: manual 
