apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  containers:
  - args:
    - sleep
    - 1d
    image: busybox
    name: backend
  # dnsPolicy: ClusterFirst
  # restartPolicy: Always
