--- 
apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-gpu
  labels:
    app: machineruuning
spec:
  containers:
  - name: tensorflow 
    image: tensorflow/tensorflow:nightly-jupyter
    ports:
      - containerPort: 8888
  nodeSelector:
    disktype: "ssd"
    gpu: "true"